---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5d3c0fa7f2a5a100129f9b06/webhook/forestry
sections:
- type: document
  path: site-metadata.json
  label: Global Site Config
  templates:
  - config
- type: document
  path: src/data/socials.json
  label: Social Links
  templates:
  - social
- type: directory
  path: src/pages/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: src/pages
  label: Blogs
  create: all
  match: "**/*"
  templates:
  - blog
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  instant_preview_command: npm run forestry:preview
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
